version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'scrape'
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'user_pass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root_pass'
    # command: --disable-partition-engine-check
    # command: --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0 --log_bin=ON
    command: [--ignore-db-dir=lost+found]
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./database:/var/lib/mysql
      # - my-db:/var/lib/mysql
# Names our volume
# volumes:
#   my-db:
